### ISSUE TITLE
No write permissions on Packages folder of Marathon

### ISSUE THREAD

**Issue by Jelle-elaut** [JohnSundell/Marathon#151]
Hello!
I tried installing the Xcode theme found on https://github.com/johnsundell/xcodetheme
Whenever I run the script, I get the following error: 

`💥  Failed to update packages
👉  Make sure you have write permissions to the folder '/Users/jelleelaut/.marathon/Packages/'`

Even when I delete the .marathon folder, it gets recreated and I get the same error.
Thanks for the help!

**Comment by kaishin** [comment]
I have the same issue on 10.13.2.

**Comment by kaishin** [comment]
Try running the install command with the `--verbose` flag.

This doesn't seem to be related to permissions in my case, but rather to Swift version mismatch. That error message is misleading.

**Comment by kballard** [comment]
I'm getting this too. It's very user-unfriendly. In fact, attempting to install a package that uses an old version of Swift breaks Marathon entirely such that a simple `marathon create foo.swift` fails with this same incorrect error (as it tries to declare a dependency on the broken package, which SPM says it can't find).

**Comment by amadeu01** [comment]
I have the same issue on 10.13.4.

**Comment by tweetjay** [comment]
Same for me

**Comment by Sega-Zero** [comment]
@JohnSundell any news on this? [Cannot use](https://github.com/danger/danger-swift/issues/63) danger-swift because of it

**Comment by sunshinejr** [comment]
@Sega-Zero the problem with `--enable-prefetching` option is already fixed on version 2.1.0, released 5 hours ago. Did you try this one?

**Comment by Sega-Zero** [comment]
yep, it's still there. should I install danger-swift other way than brew to use a newer version of Marathon?

**Comment by sunshinejr** [comment]
Seems like John moved the prefered installation method from `Homebrew` to `Make` as the releases are delayed. Probably not there yet on brew, [try using `make` instead](https://github.com/JohnSundell/Marathon#on-macos) and let us know!

**Comment by Sega-Zero** [comment]
Nope. It's still there:
```swift
danger process danger-swift
Updating packages...
$ cd "/Users/user/workspace/dir/" && /usr/bin/env xcrun --sdk macosx swift --version
Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
Target: x86_64-apple-darwin17.5.0
$ cd "/Users/user/.danger-swift/Packages/Generated/" && /usr/bin/env xcrun --sdk macosx swift package --enable-prefetching update
error: unknown option --enable-prefetching; use --help to list available options

Error:  TypeError: Cannot read property 'concat' of undefined
    at Object.exports.mergeResults (/usr/local/lib/node_modules/danger/distribution/commands/utils/reporting.js:15:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:99:51)
    at step (/usr/local/lib/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:32:23)
    at Object.next (/usr/local/lib/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:13:53)
    at /usr/local/lib/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:7:71
    at __awaiter (/usr/local/lib/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:3:12)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:87:48)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
script returned exit code 1
```

Is there a way to tell danger-swift to use Marathon from /usr/local/bin?

**Comment by sunshinejr** [comment]
Oh, this seems like a Danger issue, not a Marathon one. We need a new release on brew. Not sure if it's possible to change the bin dependency, but you should be able to build `danger-swift` by cloning the repo and using `make install`. I suggest moving this convo to https://github.com/danger/danger-swift/issues/63 instead, so we won't spam this issue here 😉

**Comment by kballard** [comment]
The original issue can't only happen on high sierra, because it happened to me on sierra.

**Comment by 0x7fffffff** [comment]
Can confirm the home brew issue. I had this problem when I installed with home-brew, but not after uninstalling and reinstalling with make.

**Comment by kballard** [comment]
I had this problem when I installed using Mint.

**Comment by JohnSundell** [comment]
Would be really awesome if one of you who are experiencing this issue could spend some time debugging it and maybe come up with a solution? It doesn't happen to me on the latest `master`, so would be great if someone who can reproduce this on their machine could dig into it so we can find a fix 🙂 I'm happy to answer any questions about the implementation if you need any help 👍

**Comment by kballard** [comment]
@JohnSundell When I was hitting this problem, the trigger was attempting to install a package that uses an old version of Swift (and therefore doesn't compile with the current Swift). Have you tried doing something like that?

**Comment by JohnSundell** [comment]
@kballard Ah nice, I'm able to reproduce it now! Still don't know if and when I'll have time to work on a fix, but since we now have concrete reproduction steps it should be something anyone could jump in and debug 👍

**Comment by tranlily** [comment]
I came up with the solution.

If you are following the tutorial from: https://github.com/JohnSundell/XcodeTheme

You're suggesting to install Marathon using:
`$ brew install marathon-swift`

It's because it's not up to date. Given that you're using Xcode, I'm assuming you're on macOS. I followed these steps instead from: https://github.com/JohnSundell/Marathon

**On macOS
Using Make (recommended):**
`$ git clone https://github.com/JohnSundell/Marathon.git
$ cd Marathon
$ make`


After you have done this, then you can successfully run
`$ marathon run johnsundell/xcodetheme`

**Comment by haemi** [comment]
@tranlily so there is no way with `brew` ? That's a pitty as I love the updating system of brew... When installing via `make` I always have to check for updates myself, right?

**Comment by JohnSundell** [comment]
I'd love for Marathon to fully support Homebrew and be updated regularly, but I personally don't use it and find dealing with Homebrew very time consuming, so changes are low I'll be motivated & able to find the time to keep it up to date. The best would be to set up some form of automatic pipeline so that new releases are automatically published on Homebrew. If someone wants to contribute something like that (if it's even possible) I'd be happy to add it 👍

**Comment by carlogilmar** [comment]
Today I tried to install with brew, but I couldn't... I had to install via make

**Comment by mxcl** [comment]
We submitted an update for marathon to brew, but in fact this exact error is occurring during the brew CI process:

https://github.com/Homebrew/homebrew-core/pull/32338

**Comment by jsorge** [comment]
I created a new package and pushed a revision to it a couple fo days ago. It's using Swift 4.2 as the package version (the package is here: https://github.com/jsorge/maverick-models.git). When I try to add it to Marathon I get the same messages being reported here:
```
   Updating packages...
💥  Failed to update packages
👉  Make sure you have write permissions to the folder '/Users/jsorge/.marathon/Packages/'
```
If I remove the package all goes back to normal and I can edit scripts again.

**Comment by duemunk** [comment]
I'm still seeing this error message when running in a folder a folder with a & character (ampersand).

```
cd Test\&ing
marathon run johnsundell/xcodetheme --verbose
```

This outputs
```
🏃  Cloning https://github.com/johnsundell/xcodetheme.git...
   $ cd "/Users/tobiasdm/.marathon/Scripts/Temp/https---github.com-johnsundell-xcodetheme.git/" && git clone https://github.com/johnsundell/xcodetheme.git clone -q
   
   $ cd "/Users/tobiasdm/.marathon/Scripts/Cache/-Users-tobiasdm-.marathon-Scripts-Temp-https---github.com-johnsundell-xcodetheme.git-clone-Install/" && readlink OriginalFile
   /Users/tobiasdm/.marathon/Scripts/Temp/https---github.com-johnsundell-xcodetheme.git/clone/Install.swift
   $ cd "/Users/tobiasdm/Desktop/Test&ing/" && /usr/bin/env xcrun --sdk macosx swift package --version
   /bin/bash: ing/: No such file or directory
💥  Failed to create a Package.swift file for the script
👉  Make sure you have write permissions to the folder '/Users/tobiasdm/.marathon/Scripts/Cache/-Users-tobiasdm-.marathon-Scripts-Temp-https---github.com-johnsundell-xcodetheme.git-clone-Install/'
```

Understandably this doesn't fly: `/bin/bash: ing/: No such file or directory`. So it seems that Marathon doesn't escape odd characters properly.
